name: Co-working and Co-living in Spanish village
favicon: null
layout_spectrum: 0.7635822026059031
typography_spectrum: 0.05235674767754972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10150f'
    - '#7ca9e2'
    - '#e5e5ef'
    - '#6d7d3f'
    - '#444f28'
  brandStrength: 0.6875
  lightness: 0.9151052199304104
  saturation: 0.8631820729933679
  rhythmicContrast: 0.04165801405906677
purpose: []
