name: Co-working and Co-living in Spanish village
favicon: null
layout_spectrum: 0.90162
typography_spectrum: 0.07317
title: Nature based location for independent entrepreneurs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10150f'
    - '#7ca9e2'
    - '#e5e5ef'
    - '#6d7d3f'
    - '#444f28'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
